// MAKEHELP.BAT generated Help Map file.  Used by DRAFTCABLE.HPJ. 
 
// Commands (ID_* and IDM_*) 
#define HID_VIEW_ARRANGE                        0x1007F
#define HID_EDITTB1                             0x10408
#define HID_DELTB1                              0x10409
#define HID_NEWTB1                              0x1040A
#define HID_NEWTB2                              0x1040B
#define HID_EDITTB2                             0x1040C
#define HID_DELTB2                              0x1040D
#define HID_CHANGE_FONT                         0x10412
#define HID_BUTTON_RECT                         0x18003
#define HID_NEXT_FIELD                          0x18003
#define HID_BUTTON_ELLIPSE                      0x18004
#define HID_OK                                  0x18004
#define HID_BUTTON_SELECT                       0x18005
#define HID_CANCEL                              0x18005
#define HID_BUTTON_LINE                         0x18006
#define HID_BUTTON_ARC                          0x18007
#define HID_BUTTON_BOARD                        0x18008
#define HID_PLACE_PART                          0x18009
#define HID_PLACE_WIRE                          0x1800A
#define HID_PLACE_BUSENTRY                      0x1800B
#define HID_SELECT_NET                          0x1800C
#define HID_ZOOM_IN                             0x1800D
#define HID_ZOOM_OUT                            0x1800E
#define HID_EDIT_PART                           0x1800F
#define HID_SNAP_TOGRID                         0x18010
#define HID_PLACE_NETALIAS                      0x18011
#define HID_PLACE_PIN                           0x18012
#define HID_BUTTON_POLYLINE                     0x18013
#define HID_ARCHIVO_GENCABLE                    0x18014
#define HID_ESCAPE                              0x18015
#define HID_ROTATE                              0x18016
#define HID_TOOL_OPTION_PAGE                    0x18017
#define HID_FILE_NEW_COMPONENTE                 0x18018
#define HID_BUTTON32793                         0x18019
#define HID_TOOL_CONFIG                         0x1801B
#define HID_ORDER_TOP                           0x1801C
#define HID_ORDER_BOTTOM                        0x1801D
#define HID_SUP                                 0x1801E
#define HID_EDIT_NETALIAS                       0x1801F
#define HID_EDIT_RACK                           0x18021
#define HID_FILE_NEW_RACK                       0x18022
#define HID_PLACE_CHASSIS                       0x18023
#define HID_SNAP_TOGRID2                        0x18024
#define HID_FILE_NEW_PATCHP                     0x18025
#define HID_BUTTON_RULE                         0x18026
#define HID_ZOOM_ALL                            0x18027
#define HID_ZOOM_AREA                           0x1802A
#define HID_BUTTON32811                         0x1802B
#define HID_BUTTON32812                         0x1802C
#define HID_ZOOM_CURSORPLUS                     0x1802D
#define HID_ZOOM_CURSORMINUS                    0x1802E
#define HID_PLACE_BUS                           0x1802F
#define HID_PLACE_NOCON                         0x18030
#define HID_PLACE_PORT                          0x18033
#define HID_PLACE_TEXT                          0x18035
#define HID_PLACE_PICTURE                       0x18036
#define HID_FILE_NEW_SHEET                      0x18039
#define HID_DEBUG_EDIT_SHPINFO                  0x1803A
#define HID_0_1                                 0x18041
#define HID_PLACE_BUSJUNC                       0x18042
#define HID_TOOL_SIC                            0x18044
#define HID_PLACE_PORTRIGHT                     0x18047
#define HID_IMG_ROTATE                          0x18048
#define HID_IMG_FLIPHORZ                        0x18049
#define HID_IMG_FLIPVERT                        0x1804A
#define HID_IMG_POLYGONPOPUP                    0x1804B
#define HID_EDIT_PROPERTIES                     0x1804C
#define HID_EDIT_TB                             0x1804D
#define HID_BUTTON_CURVE                        0x1804E
#define HID_INDICATOR_TOOL                      0x1E706
#define HID_INDICATOR_COOR                      0x1E707
#define HID_INDICATOR_MODE                      0x1E708
 
// Prompts (IDP_*) 
 
// Resources (IDR_*) 
#define HIDR_MAINFRAME                          0x20080
#define HIDR_DRAFTDTYPE                         0x20081
#define HIDR_DRAWING                            0x20082
#define HIDR_PLACE                              0x2008D
#define HIDR_PLACE1                             0x2008E
#define HIDR_CONTEXT                            0x20090
#define HIDR_PATCHPTYPE                         0x20091
#define HIDR_DEBUG_CONTEXT                      0x200A9
#define HIDR_EDITDROPDOWN                       0x200AA
#define HIDR_CABLEDIT                           0x200CA
#define HIDR_MAINFRAME1                         0x200CB
#define HIDR_FOLDERTABS                         0x2F232
 
// Dialogs (IDD_*) 
#define HIDD_ABOUTBOX                           0x20064
#define HIDD_TBEDIT_FORM                        0x20065
#define HIDD_CABLEDIT                           0x20081
#define HIDD_NETALIAS                           0x20092
#define HIDD_PIN                                0x20093
#define HIDD_PLACEPART                          0x20094
#define HIDD_PARTEDIT                           0x20095
#define HIDD_PAGESIZE                           0x2009C
#define HIDD_CONFIG                             0x2009D
#define HIDD_SAVEAS                             0x200A0
#define HIDD_PAGEGRID                           0x200A2
#define HIDD_PATCHPPROP                         0x200A3
#define HIDD_TEXT                               0x200A4
#define HIDD_PLACEPART2                         0x200A7
#define HIDD_DEBUG_SHPINFO                      0x200AA
#define HIDD_NAME                               0x200AB
#define HIDD_NETLIST                            0x200AC
#define HIDD_SAVEASDB                           0x200BB
#define HIDD_PARTPROP                           0x200C2
 
// Frame Controls (IDW_*) 
