//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DraftDraw.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_TBEDIT_FORM                 101
#define ID_VIEW_ARRANGE                 127
#define IDR_MAINFRAME                   128
#define IDR_DRAFTDTYPE                  129
#define IDD_CABLEDIT                    129
#define IDR_DRAWING                     130
#define IDC_CURSOR_4W                   132
#define IDI_ARROW_LEFT                  132
#define IDC_CURSOR_EW                   133
#define IDI_ARROW_RIGHT                 133
#define IDC_CURSOR_NE                   134
#define IDC_CURSOR_NS                   135
#define IDC_CURSOR_NW                   136
#define IDR_PLACE                       141
#define IDR_PLACE1                      142
#define IDR_CONTEXT                     144
#define IDR_PATCHPTYPE                  145
#define IDD_NETALIAS                    146
#define IDD_PIN                         147
#define IDD_PLACEPART                   148
#define IDC_DRAW                        149
#define IDD_PARTEDIT                    149
#define IDI_FOLDER_OPEN                 150
#define IDI_FOLDER_CLOSE                151
#define IDI_HARDDRV                     152
#define IDI_MYCOMP                      153
#define IDD_PAGESIZE                    156
#define IDD_CONFIG                      157
#define IDC_PENCIL                      159
#define IDD_SAVEAS                      160
#define IDB_BITMAP1                     161
#define IDB_BITMAP2                     162
#define IDD_PAGEGRID                    162
#define IDD_PATCHPPROP                  163
#define IDC_ZOOM_PLUS                   164
#define IDD_TEXT                        164
#define IDC_ZOOM_MINUS                  165
#define IDB_BITMAP3                     166
#define IDD_PLACEPART2                  167
#define IDI_SHEET                       168
#define IDR_DEBUG_CONTEXT               169
#define IDD_DEBUG_SHPINFO               170
#define IDR_EDITDROPDOWN                170
#define IDD_NAME                        171
#define IDD_NETLIST                     172
#define IDB_BITMAP_DTLS                 173
#define IDB_BITMAP_LIST                 174
#define IDB_BITMAP_LRGIC                175
#define IDI_LRGIC                       176
#define IDI_DTLS                        177
#define IDI_LIST                        178
#define IDI_DOCWIRING                   179
#define IDB_TBRACK                      180
#define IDB_TBRACK_SEL                  181
#define IDI_UNDO                        181
#define IDI_REDO                        182
#define IDB_PATTERN1                    183
#define IDB_PATTERN1_10                 184
#define IDB_PATTERN1_48                 185
#define IDD_SAVEASDB                    187
#define IDI_DB                          189
#define IDI_LIBRARY                     190
#define IDI_PART                        191
#define IDI_PARTRACK                    192
#define IDB_MENU_POLYGON_RECT           193
#define IDB_MENU_POLYGON_PARALEL        194
#define IDD_PARTPROP                    194
#define IDB_MENU_POLYGON_TRAP           195
#define IDB_MENU_POLYGON_ROMBO          196
#define IDB_MENU_POLYGON_TRIANG         197
#define IDB_MENU_POLYGON_PENT           198
#define IDB_MENU_POLYGON_HEX            199
#define IDB_MENU_POLYGON_OCT            200
#define IDB_MENU_POLYGON_CROSS          201
#define IDB_MENU_POLYGON_NGEAR          202
#define IDR_CABLEDIT                    202
#define IDB_MENU_POLYGON_NSTAR          203
#define IDR_MAINFRAME1                  203
#define IDD_GRAPH_DEN                   203
#define IDB_MENU_POLYGON_NPOLYGON       204
#define IDC_ROTATE                      204
#define IDB_MENU_POLYGON_NCROSS         205
#define IDB_MENU_POLYGON_T              206
#define IDB_MENU_POLYGON_L              207
#define IDB_MENU_POLYGON_STRAIGHT       208
#define IDC_ALIAS                       1000
#define IDC_VERTICAL                    1001
#define IDC_LIST1                       1001
#define IDC_COMBO_NUMBER                1002
#define IDC_COMBO_SHAPE                 1003
#define IDC_FILE                        1003
#define IDC_LISTPART                    1004
#define IDC_NAME                        1005
#define IDC_PROPERTY                    1006
#define IDC_JACK                        1009
#define IDC_COMBO_TYPE                  1010
#define IDC_STATIC_TYPE                 1011
#define IDC_STATIC_NUMBER               1012
#define IDC_SIZEFT                      1014
#define IDC_RADIO_A4                    1016
#define IDC_RADIO_A3                    1017
#define IDC_RADIO_CUSTOM                1018
#define IDC_WIDTH                       1019
#define IDC_HEIGHT                      1020
#define IDC_RADIO_MILLIM                1021
#define IDC_RADIO_INCH                  1022
#define IDC_EDIT1                       1024
#define IDC_EXAM                        1025
#define IDC_BUTTON_SAVE                 1026
#define IDC_BUTTON_SAVEAS               1027
#define IDC_BUTTON_NEW                  1028
#define IDC_COMBO1                      1029
#define IDC_BUTTON_EDIT                 1030
#define IDC_LIST2                       1031
#define ID_EDITTB1                      1032
#define ID_DELTB1                       1033
#define ID_NEWTB1                       1034
#define ID_NEWTB2                       1035
#define ID_EDITTB2                      1036
#define ID_DELTB2                       1037
#define IDC_FILE1                       1038
#define IDC_NAME2                       1039
#define IDC_FILE2                       1040
#define IDC_NAME1                       1041
#define ID_CHANGE_FONT                  1042
#define IDC_FONT                        1043
#define IDC_TEXT1                       1044
#define IDC_TEXT                        1045
#define IDC_BUTTON_ICONBIG              1046
#define IDC_BUTTON_LIST                 1047
#define IDC_BUTTON_DETAILS              1048
#define IDC_RADIO_ALL                   1049
#define IDC_RADIO_SHEETCUR              1050
#define IDC_RADIO_SHEET                 1051
#define IDC_EDIT_SHEET                  1052
#define IDC_BUTTON_EDITLABEL            1053
#define IDC_BUTTON_DEL                  1055
#define IDC_TREE1                       1056
#define IDC_BUTTON_NEWLIB               1058
#define IDC_ADODC1                      1059
#define IDC_BUTTON_NEWLIB2              1059
#define IDC_BUTTON_IMPLIB               1059
#define IDC_DATAGRID1                   1060
#define IDC_CHECK_ALL                   1061
#define IDC_CHECK1                      1062
#define IDC_CHECK_TOGGLE_CAB_CON        1062
#define IDS_MENU_POLYGON_FIRST          2000
#define IDS_MENU_POLYGON_RECT           2001
#define IDS_MENU_POLYGON_PARALEL1       2002
#define IDS_MENU_POLYGON_TRAP           2003
#define IDS_MENU_POLYGON_ROMBO          2004
#define IDS_MENU_POLYGON_TRIANG         2005
#define IDS_MENU_POLYGON_PENT           2006
#define IDS_MENU_POLYGON_HEX            2007
#define IDS_MENU_POLYGON_OCT            2008
#define IDS_MENU_POLYGON_CROSS          2009
#define IDS_MENU_POLYGON_NGEAR          2010
#define IDS_MENU_POLYGON_NSTAR          2011
#define IDS_MENU_POLYGON_NPOLYGON       2012
#define IDS_MENU_POLYGON_T              2013
#define IDS_MENU_POLYGON_L              2014
#define IDS_MENU_POLYGON_STRAIGHT       2015
#define IDS_MENU_POLYGON_NCROSS         2016
#define ID_BUTTON_RECT                  32771
#define ID_NEXT_FIELD                   32771
#define ID_BUTTON_ELLIPSE               32772
#define ID_OK                           32772
#define ID_BUTTON_SELECT                32773
#define ID_CANCEL                       32773
#define ID_BUTTON_LINE                  32774
#define ID_BUTTON_ARC                   32775
#define ID_BUTTON_BOARD                 32776
#define ID_PLACE_PART                   32777
#define ID_PLACE_WIRE                   32778
#define ID_PLACE_BUSENTRY               32779
#define ID_SELECT_NET                   32780
#define ID_ZOOM_IN                      32781
#define ID_ZOOM_OUT                     32782
#define ID_EDIT_PART                    32783
#define ID_SNAP_TOGRID                  32784
#define ID_PLACE_NETALIAS               32785
#define ID_PLACE_PIN                    32786
#define ID_BUTTON_POLYLINE              32787
#define ID_ARCHIVO_GENCABLE             32788
#define ID_ESCAPE                       32789
#define ID_ROTATE                       32790
#define ID_TOOL_OPTION_PAGE             32791
#define ID_FILE_NEW_COMPONENTE          32792
#define ID_BUTTON32793                  32793
#define ID_TOOL_CONFIG                  32795
#define ID_ORDER_TOP                    32796
#define ID_ORDER_BOTTOM                 32797
#define ID_SUP                          32798
#define ID_EDIT_NETALIAS                32799
#define ID_EDIT_RACK                    32801
#define ID_FILE_NEW_RACK                32802
#define ID_PLACE_CHASSIS                32803
#define ID_SNAP_TOGRID2                 32804
#define ID_FILE_NEW_PATCHP              32805
#define ID_BUTTON_RULE                  32806
#define ID_ZOOM_ALL                     32807
#define ID_ZOOM_AREA                    32810
#define ID_BUTTON32811                  32811
#define ID_BUTTON32812                  32812
#define ID_ZOOM_CURSORPLUS              32813
#define ID_ZOOM_CURSORMINUS             32814
#define ID_PLACE_BUS                    32815
#define ID_PLACE_NOCON                  32816
#define ID_PLACE_PORT                   32819
#define ID_PLACE_TEXT                   32821
#define ID_PLACE_PICTURE                32822
#define ID_FILE_NEW_SHEET               32825
#define ID_DEBUG_EDIT_SHPINFO           32826
#define ID_0_1                          32833
#define ID_PLACE_BUSJUNC                32834
#define ID_TOOL_SIC                     32836
#define ID_PLACE_PORTRIGHT              32839
#define ID_IMG_ROTATE                   32840
#define ID_IMG_FLIPHORZ                 32841
#define ID_IMG_FLIPVERT                 32842
#define ID_IMG_POLYGONPOPUP             32843
#define ID_EDIT_PROPERTIES              32844
#define ID_EDIT_TB                      32845
#define ID_BUTTON_CURVE                 32846
#define ID_FILE_SAVE_SHEET_CURRENT      32847
#define ID_PLACE_SHEETS                 32848
#define ID_VIEW_GRAPH_DEN               32849
#define ID_BUTTON_ROTATE                32850
#define ID_BUTTON32857                  32857
#define ID_BUTTON32858                  32858
#define ID_BUTTON_PAN                   32858
#define ID_BUTTON_POLYARC               32859
#define ID_INDICATOR_TOOL               59142
#define ID_INDICATOR_COOR               59143
#define ID_INDICATOR_MODE               59144
#define IDS_MSG_CABLEXISTS              62000
#define IDS_MSG_PATCHPCHANGE            62001
#define IDR_FOLDERTABS                  62002
#define IDS_MSG_CONFDEL1                62003
#define IDS_MSG_CONFDELN                62004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        207
#define _APS_NEXT_COMMAND_VALUE         32859
#define _APS_NEXT_CONTROL_VALUE         1063
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
